const EXP = [
  {
    role: "undergrad student",
    title: "@UMD",
    dates: "august 2022 — present",
    desc: "information science major, data science minor. somewhere between a cs degree and an identity crisis. graduating may 2026.",
    techs: ["language-python"],
    icon: "umd",
  },
  {
    role: "ai/data intern",
    title: "@NewYorkLife",
    dates: "may 2025 — august 2025",
    desc: "worked as a data & ai engineering intern where i conducted performance analysis to improve team scalability, retention, and operational efficiency. developed a centralized analytics tool by consolidating fragmented data sources, enabling cross-unit insights and faster reporting. automated reporting workflows using python, vbscript, and excel, significantly reducing manual effort and error rates.",
    techs: ["language-python"],
    icon: "nyl",
  },
  {
    role: "full stack swe",
    title: "@Hack4Impact",
    dates: "september 2024 — june 2025",
    desc: "contributed to building impactful software for nonprofits at hack4impact. developed a grant management application using firebase and react for the children's cancer foundation, reducing administrative workload and accelerating grant processing time. participated in agile development including sprint planning and code reviews.",
    techs: ["react", "firebase", "language-typescript"],
    icon: "h4i",
  },
  {
    role: "prompt engineer",
    title: "@NatureConservancy",
    dates: "february 2025 — march 2025",
    desc: "participated in a 7-week microsoft tsi initiative to build an ai-powered chatbot improving website usability for the nature conservancy. focused on prompt design and persona experimentation to refine conversational tone and responsiveness. built with azure services for scalable backend integration and blazor (c#) for the frontend.",
    techs: ["language-csharp"],
    icon: "tnc",
  },
  {
    role: "swe intern",
    title: "@SomyTech",
    dates: "june 2024 — august 2024",
    desc: "built a secure document storage backend in python with fastapi, postgresql, and jwt auth. wired up aws (s3, sqs, ec2) for storage, messaging, and hosting. set up ci/cd pipelines via github actions and tested everything with postman.",
    techs: ["language-python", "language-aws", "language-postgresql"],
    icon: "",
  },
];
