const PROJECTS = [
  {
  name: "chess engine.",
  year: "coming soon",
  sub: "rust goes brr.",
  desc: "a simple chess engine built in rust. cus why not.",
  link: "",
  techs: ["language-rust"],
},
{
  name: "popcorn.",
  year: "2024",
  sub: "just watch something already.",
  desc: "a rust cli that pulls your letterboxd watchlist and picks a random movie for you. for when decision paralysis hits harder than the movie ever could.",
  link: "https://github.com/mistahanish/popcorn",
  techs: ["language-rust"],
},
  {
  name: "fmri vr.",
  year: "2024",
  sub: "immersive 3d brain scan visualization for doctors.",
  desc: "react + vite web portal with supabase backend and google oauth for secure patient fmri data management. bids-compliant file storage with signed urls, and a unity c# vr frontend backed by python services for real-time 3d brain exploration.",
  link: "https://github.com/tanikajangam/HopHacks2025",
  techs: ["react", "unity", "language-python", "language-csharp"],
},
  {
  name: "my digital totoro.",
  year: "2025",
  sub: "a tamagotchi that lives in your arduino.",
  desc: "arduino mkr iot carrier rev2 running sprite animations with a react typescript webapp for remote care. synced to arduino iot cloud over mqtt so you could feed totoro from class.",
  link: "https://github.com/mistahanish/MyDigitalTotoro",
  techs: ["language-cpp", "react", "language-typescript"],
},
  {
    name: "circa.",
    year: "2025",
    sub: "circadian rhythm tracker.",
    desc: "built a daily energy tracking app using react, firebase, and tailwindcss, letting users log and visualize their energy levels across a 24-hour cycle. real-time firestore storage updates graphs dynamically as new entries are added.",
    link: "https://guanglinwei.github.io/circa/",
    techs: ["react", "language-typescript", "firebase"],
  },
  {
    name: "linky.",
    year: "2025",
    sub: "multiplayer semantic word association game.",
    desc: "built with a friend for a competition. a real-time multiplayer game where players make semantic word associations. not my best work but a fun build.",
    link: "https://github.com/mistahanish/buildathon",
    techs: ["react", "language-typescript", "language-python"],
  },
  {
    name: "portfolio.",
    year: "updated 2026",
    sub: "the website you are on rn :0",
    desc: "my portfolio showcasing not only my projects, but also showcasing me and who i am.",
    link: "https://hanishv.com",
    techs: ["language-html5", "language-css3", "language-javascript"],
  },
  {
    name: "poker flip.",
    year: "2023",
    sub: "simple poker hand flipping app.",
    desc: "bitcamp 2023 project with a friend. i guess i really do love poker.",
    link: null,
    techs: ["react", "language-typescript"],
  },
];

  // {
  //   name: "cash claw.",
  //   year: "2024",
  //   sub: "ok literally don't even look at this.",
  //   desc: "i actually do not know what my teammates were thinking when they entered this into a hackathon.",
  //   link: "https://github.com/guanglinwei/CashClaw",
  //   techs: ["react"],
  // },