const PROJECTS = [
  //   {
  //   name: "chess engine.",
  //   year: "coming soon",
  //   sub: "rust goes brr.",
  //   desc: "a simple chess engine built in rust. cus why not.",
  //   link: "",
  //   techs: ["language-rust"],
  // },
  {
    name: "space attorney",
    year: "2026",
    sub: "court is now in session. unfortunately.",
    desc: "a two-player debate settler where each side submits their argument on their own screen and an ai judge delivers the verdict in ace attorney style. hand-drawn animations included because we had something to prove. built at bitcamp 2026.",
    link: null,
    techs: ["language-typescript", "react"],
    cdImg: "attorney",
  },
  {
    name: "popcorn",
    year: "2025",
    sub: "just watch something already.",
    desc: "a rust cli that pulls your letterboxd watchlist and picks a random movie for you. for when decision paralysis hits harder than the movie ever could.",
    link: "https://github.com/mistahanish/popcorn",
    techs: ["language-rust"],
    cdImg: "popcorn",
  },
  {
    name: "fmri vr",
    year: "2025",
    sub: "immersive 3d brain scan visualization for doctors.",
    desc: "react + vite web portal with supabase backend and google oauth for secure patient fmri data management. bids-compliant file storage with signed urls, and a unity c# vr frontend backed by python services for real-time 3d brain exploration.",
    link: "https://github.com/tanikajangam/HopHacks2025",
    techs: ["react", "unity", "language-python", "language-csharp"],
    cdImg: "fmri",
  },
  {
    name: "my digital totoro",
    year: "2025",
    sub: "a tamagotchi that lives in your arduino.",
    desc: "arduino mkr iot carrier rev2 running sprite animations with a react typescript webapp for remote care. synced to arduino iot cloud over mqtt so you could feed totoro from class.",
    link: "https://github.com/mistahanish/MyDigitalTotoro",
    techs: ["language-cpp", "react", "language-typescript"],
    cdImg: "totorocd1",
  },
  {
    name: "circa",
    year: "2025",
    sub: "circadian rhythm tracker.",
    desc: "built a daily energy tracking app using react, firebase, and tailwindcss, letting users log and visualize their energy levels across a 24-hour cycle. real-time firestore storage updates graphs dynamically as new entries are added.",
    link: "https://guanglinwei.github.io/circa/",
    techs: ["react", "language-typescript", "firebase"],
    cdImg: "circa",
  },
  {
    name: "linky",
    year: "2024",
    sub: "multiplayer semantic word association game.",
    desc: "built with a friend for a competition. a real-time multiplayer game where players make semantic word associations. not my best work but a fun build.",
    link: "https://github.com/mistahanish/buildathon",
    techs: ["react", "language-typescript", "language-python"],
    cdImg: "linky",
  },
  {
    name: "portfolio",
    year: "updated 2026",
    sub: "the website you are on rn :0",
    desc: "built from the ground up in pure html, css, and javascript. not only showcases my projects, but also who i am",
    link: "https://hanishv.com",
    techs: ["language-html", "language-css", "language-javascript"],
    cdImg: null,
  },
];

// {
//   name: "cash claw.",
//   year: "2024",
//   sub: "ok literally don't even look at this.",
//   desc: "i actually do not know what my teammates were thinking when they entered this into a hackathon.",
//   link: "https://github.com/guanglinwei/CashClaw",
//   techs: ["react"],
// },

// {
//   name: "poker flip.",
//   year: "2023",
//   sub: "simple poker hand flipping app.",
//   desc: "bitcamp 2023 project with a friend. i guess i really do love poker.",
//   link: null,
//   techs: ["react", "language-typescript"],
// },
